language: node_js

node_js:
    - node

cache:
    - npm

install:
    - npm install

before_script:
    - npm install --save-dev coveralls

script:
    - npm run lint
    - npm run test:coverage
    - npx nyc report --reporter=text-lcov | coveralls